unordered_map_hash:unordered_map_hash.cpp
	g++ unordered_map_hash.cpp -o unordered_map_hash -std=c++17

unordered_map_hash_v2:unordered_map_hash_v2.cpp
	g++ unordered_map_hash_v2.cpp -o unordered_map_hash_v2 -std=c++17

hello: hello.cpp
	g++ hello.cpp -o hello -std=c++17
world: world.cpp
	g++ world.cpp -o world -std=c++17
clean:
	rm -rf unordered_map_hash unordered_map_hash_v2